FROM alpine
LABEL vendor=DHUniWien

RUN apk update \
 && apk upgrade \
 && apk add \
    python3 \
    py-lxml \
    py-yaml \
    py-requests \
    openjdk8-jre \
    git \
    openssh

RUN pip3 install bs4
