FROM alpine
LABEL vendor=DHUniWien

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
    python3 \
    py-lxml \
    py-yaml \
    py-requests \
    openjdk8-jre \
    git \
    openssh \
    libxml2-utils \
    curl \
    jp \
    graphviz \
    tzdata

# timezone Europe/Vienna
RUN cp /usr/share/zoneinfo/Europe/Vienna /etc/localtime && \
    echo "Europe/Vienna" > /etc/timezone && \
    apk del tzdata

RUN pip3 install bs4
