FROM alpine
LABEL vendor=DHUniWien

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
    python3 \
    py-lxml \
    py-yaml \
    py-requests \
    openjdk8-jre \
    git \
    openssh \
    libxml2-utils \
    curl \
    jq \
    graphviz \
    tzdata \
    # BEGIN Text::Tradition
    make \
    gcc \
    wget \
    perl \
    perl-xml-libxml \
    perl-dev \
    libc-dev \
    perl-text-csv \
    perl-spreadsheet-parseexcel \
    perl-ipc-run \
    perl-moose \
    perl-test-warn \
    perl-data-dump \
    perl-algorithm-diff \
    perl-graph \
    perl-file-which \
    perl-devel-stacktrace \
    perl-json
    # END Text::Tradition

RUN wget https://cpanmin.us -O cpanm && \
    perl cpanm Text::Tradition

# timezone Europe/Vienna
RUN cp /usr/share/zoneinfo/Europe/Vienna /etc/localtime && \
    echo "Europe/Vienna" > /etc/timezone && \
    apk del tzdata

RUN pip3 install bs4
