---
resources:
    - name: tpen2tei-sources
      type: git
      source:
        uri: {{tpen2tei-sources}}
        branch: {{tpen2tei-branch}}

    - name: tools-sources
      type: git
      source:
        uri: {{tools-sources}}
        branch: {{tools-branch}}
        paths: [src, ci/resources]

    - name: tools-config-sources
      type: git
      source:
        uri: {{tools-config-sources}}
        branch: {{tools-config-branch}}
        private_key: {{DHUniWienMU-priv-key}}

    - name: tools-final-image
      type: docker-image
      source:
        repository: {{tools-final-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: collatex-sources
      type: git
      source:
        uri: {{collatex-sources}}
        paths: [collatex-core, collatex-tools, ci/resources]

    - name: maven-config
      type: git
      source:
        uri: {{maven-config-uri}}
        private_key: {{DHUniWienMU-priv-key}}

    - name: version
      type: semver
      source:
        driver: git
        uri: {{version-uri}}
        branch: {{version-branch}}
        file: {{version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

jobs:
    - name: test-tpen2tei
      plan:
        - get: tpen2tei-sources
          trigger: true

        - task: task-test-tpen2tei

          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: {{tools-ci-image}}
                insecure_registries: [ {{insecure-registries}} ]

            inputs:
              - name: tpen2tei-sources

            outputs:
              - name: artifacts

            run:
              path: sh
              dir: tpen2tei-sources/tests
              args:
                - -exc
                - |
                  PYTHONPATH=.. python3 -m unittest discover --start-directory .


    - name: test-tpen
      plan:
        - aggregate:

          - get: tools-sources
            trigger: true
          - get: tools-config-sources

        - task: task-test-tpen

          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: {{tools-ci-image}}
                insecure_registries: [ {{insecure-registries}} ]

            inputs:
              - name: tools-sources
              - name: tools-config-sources

            outputs:
              - name: artifacts

            run:
              path: sh
              dir: tools-sources/src/tpen
              args:
                - -exc
                - |
                  cp ../../../tools-config-sources/tpen/backup.yml .
                  python3 -m unittest discover --start-directory tests/


    - name: test-collatex
      plan:
        - aggregate:
          - get: collatex-sources
            trigger: true
          - get: maven-config

        - task: task-test-collatex

          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: {{collatex-ci-image}}
                insecure_registries: [ {{insecure-registries}} ]

            inputs:
              - name: collatex-sources
              - name: maven-config

            run:
              path: sh
              args:
                - -exc
                - |
                  mkdir /root/.m2/
                  cp maven-config/settings.xml /root/.m2/
                  cd collatex-sources
                  mvn test


    - name: version
      type: semver
      source:
        driver: git
        uri: {{version-uri}}
        branch: {{version-branch}}
        file: {{version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}


    - name: build-image
      plan:
        - put: version
          params:
            bump: patch

        - aggregate:

          - get: tpen2tei-sources
            trigger: true
            passed: [test-tpen2tei]

          - get: tools-sources
            trigger: true
            passed: [test-tpen]

          - get: tools-config-sources

          - get: collatex-sources
            passed: [test-collatex]
            trigger: true

          - get: maven-config

        - task: task-package-collatex

          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: {{collatex-ci-image}}
                insecure_registries: [ {{insecure-registries}} ]

            inputs:
              - name: collatex-sources
              - name: maven-config
            outputs:
              - name: collatex

            run:
              path: sh
              args:
                - -exc
                - |
                  mkdir /root/.m2/
                  cp maven-config/settings.xml /root/.m2/
                  cd collatex-sources
                  mvn package
                  cp collatex-tools/target/collatex-tools-1.8-SNAPSHOT.jar ../collatex/collatex.jar

        - task: task-copy

          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: {{tools-ci-image}}
                insecure_registries: [ {{insecure-registries}} ]

            inputs:
              - name: tpen2tei-sources
              - name: tools-sources
              - name: tools-config-sources
              - name: collatex

            outputs:
              - name: artifacts

            run:
              path: sh
              dir: /
              args:
                - -exc
                - |
                  mkdir artifacts/tools/
                  cp -r tools-sources/src/tpen/ artifacts/tools/
                  mkdir artifacts/tools/tpen2tei/
                  cp -r tpen2tei-sources/*py artifacts/tools/tpen2tei/
                  cp tools-sources/ci/resources/Dockerfile-final artifacts/Dockerfile
                  cp tools-config-sources/tpen/backup.yml artifacts/tools/tpen/
                  cp collatex/collatex.jar artifacts/tools/collatex.jar

        - put: tools-final-image
          params:
            build: artifacts
            # resource/version-file
            tag: version/version
            tag_as_latest: True
