name: TEI XML validation
on:
  workflow_call:
    inputs:
      xml_schema:
        required: true
        type: string

jobs:
  # XML validation. Do this as a separate job so that we can choose whether or not to make this a blocking failure
  validate-tei-xml:
    runs-on: [self-hosted, Linux]
    container:
      image: ghcr.io/dhuniwien/edition-tools:master
    steps: 
      - uses: actions/checkout@v3
      - name: Validate committed XML files
        run: |
          # don't stop if a linter fails, instead make sure
          # all files are checked by swallowing the return value
          #
          verr=0
          for FILE in transcription/tei-xml/*.xml
          do
            echo === $FILE ===
            xmllint --noout --relaxng ${{ inputs.xml_schema }} "$FILE"
            ret=$?
            verr=$((verr + ret))
          done
          if [ $verr -ne 0 ]; then
            echo "Some files failed to validate"
          fi
          exit $verr
